--------------------------------------------------------
--  파일이 생성됨 - 일요일-11월-16-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACCOUNT
--------------------------------------------------------

  CREATE TABLE "BNKPROJECT"."ACCOUNT" 
   (	"ACCOUNTNO" NUMBER, 
	"USERID" NUMBER, 
	"BALANCE" NUMBER DEFAULT 0, 
	"CREATEDAT" DATE DEFAULT SYSDATE, 
	"UPDATEDAT" DATE, 
	"STATUS" CHAR(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BNKPROJECT"."ACCOUNT"."ACCOUNTNO" IS '계좌번호 (PK)';
   COMMENT ON COLUMN "BNKPROJECT"."ACCOUNT"."USERID" IS '회원 ID (FK)';
   COMMENT ON COLUMN "BNKPROJECT"."ACCOUNT"."BALANCE" IS '잔액';
   COMMENT ON COLUMN "BNKPROJECT"."ACCOUNT"."CREATEDAT" IS '생성일';
   COMMENT ON COLUMN "BNKPROJECT"."ACCOUNT"."UPDATEDAT" IS '수정일';
   COMMENT ON COLUMN "BNKPROJECT"."ACCOUNT"."STATUS" IS '계좌 상태(Y:활성/N:비활성)';
   COMMENT ON TABLE "BNKPROJECT"."ACCOUNT"  IS '사용자의 계좌 정보를 관리. 
잔액, 상태, 개설일 등을 users 테이블과 FK로 연결.';
--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

  CREATE TABLE "BNKPROJECT"."ADMIN" 
   (	"ADMINID" NUMBER, 
	"ADMINNAME" VARCHAR2(50 BYTE), 
	"LOGINID" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE), 
	"ADMINROLE" VARCHAR2(20 BYTE), 
	"CREATEDAT" DATE DEFAULT SYSDATE, 
	"UPDATEDAT" DATE, 
	"STATUS" CHAR(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BNKPROJECT"."ADMIN"."ADMINID" IS '관리자 ID (PK)';
   COMMENT ON COLUMN "BNKPROJECT"."ADMIN"."ADMINNAME" IS '관리자 이름';
   COMMENT ON COLUMN "BNKPROJECT"."ADMIN"."LOGINID" IS '로그인 계정 ID';
   COMMENT ON COLUMN "BNKPROJECT"."ADMIN"."PASSWORD" IS '로그인 계정 PW';
   COMMENT ON COLUMN "BNKPROJECT"."ADMIN"."ADMINROLE" IS '권한 그룹이름(최고|관리자| 등등)';
   COMMENT ON COLUMN "BNKPROJECT"."ADMIN"."CREATEDAT" IS '생성일';
   COMMENT ON COLUMN "BNKPROJECT"."ADMIN"."UPDATEDAT" IS '수정일';
   COMMENT ON COLUMN "BNKPROJECT"."ADMIN"."STATUS" IS '계정 상태(Y/N)';
   COMMENT ON TABLE "BNKPROJECT"."ADMIN"  IS '관리자 계정 정보를 저장.
로그인ID, 이름, 비밀번호, 권한 그룹과 연결.';
--------------------------------------------------------
--  DDL for Table BANNER
--------------------------------------------------------

  CREATE TABLE "BNKPROJECT"."BANNER" 
   (	"BANNERNO" NUMBER, 
	"BANNERNAME" VARCHAR2(100 BYTE), 
	"IMAGE" VARCHAR2(255 BYTE), 
	"STATUS" CHAR(1 BYTE) DEFAULT 'Y', 
	"CREATEDAT" DATE DEFAULT SYSDATE, 
	"UPDATEDAT" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BNKPROJECT"."BANNER"."BANNERNO" IS '배너 ID (PK)';
   COMMENT ON COLUMN "BNKPROJECT"."BANNER"."BANNERNAME" IS '배너명';
   COMMENT ON COLUMN "BNKPROJECT"."BANNER"."IMAGE" IS '이미지 경로';
   COMMENT ON COLUMN "BNKPROJECT"."BANNER"."STATUS" IS '상태(Y/N)';
   COMMENT ON COLUMN "BNKPROJECT"."BANNER"."CREATEDAT" IS '생성일';
   COMMENT ON COLUMN "BNKPROJECT"."BANNER"."UPDATEDAT" IS '수정일';
   COMMENT ON TABLE "BNKPROJECT"."BANNER"  IS '웹사이트 내 배너 이미지·링크·상태를 관리.';
--------------------------------------------------------
--  DDL for Table CATEGORY
--------------------------------------------------------

  CREATE TABLE "BNKPROJECT"."CATEGORY" 
   (	"CATEGORYID" NUMBER, 
	"CATEGORYNAME" VARCHAR2(100 BYTE), 
	"CREATEDAT" DATE DEFAULT SYSDATE, 
	"UPDATEDAT" DATE, 
	"STATUS" CHAR(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BNKPROJECT"."CATEGORY"."CATEGORYID" IS '카테고리 식별자 (PK)';
   COMMENT ON COLUMN "BNKPROJECT"."CATEGORY"."CATEGORYNAME" IS '카테고리명';
   COMMENT ON COLUMN "BNKPROJECT"."CATEGORY"."CREATEDAT" IS '생성일';
   COMMENT ON COLUMN "BNKPROJECT"."CATEGORY"."UPDATEDAT" IS '수정일';
   COMMENT ON COLUMN "BNKPROJECT"."CATEGORY"."STATUS" IS '사용 상태(Y/N)';
   COMMENT ON TABLE "BNKPROJECT"."CATEGORY"  IS '상품을 구분하는 카테고리 관리.
예금안내/예금이용가이드/금융서비스등 UI 전시용 그룹화에 사용.';
--------------------------------------------------------
--  DDL for Table CHATMESSAGE
--------------------------------------------------------

  CREATE TABLE "BNKPROJECT"."CHATMESSAGE" 
   (	"MESSAGEID" NUMBER, 
	"SESSIONID" NUMBER, 
	"SENDERTYPE" VARCHAR2(20 BYTE), 
	"MESSAGETEXT" CLOB, 
	"CREATEDAT" DATE DEFAULT SYSDATE, 
	"UPDATEDAT" DATE, 
	"SENDERID" VARCHAR2(20 BYTE), 
	"ISREAD" NUMBER(38,0) DEFAULT 0
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("MESSAGETEXT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

   COMMENT ON COLUMN "BNKPROJECT"."CHATMESSAGE"."MESSAGEID" IS '메시지 ID (PK)';
   COMMENT ON COLUMN "BNKPROJECT"."CHATMESSAGE"."SESSIONID" IS '세션 ID (FK)';
   COMMENT ON COLUMN "BNKPROJECT"."CHATMESSAGE"."SENDERTYPE" IS '발신자 구분(USER/CONSULTANT)';
   COMMENT ON COLUMN "BNKPROJECT"."CHATMESSAGE"."MESSAGETEXT" IS '메시지 내용';
   COMMENT ON COLUMN "BNKPROJECT"."CHATMESSAGE"."CREATEDAT" IS '생성일';
   COMMENT ON COLUMN "BNKPROJECT"."CHATMESSAGE"."UPDATEDAT" IS '수정일';
   COMMENT ON COLUMN "BNKPROJECT"."CHATMESSAGE"."SENDERID" IS '발신자아이디';
   COMMENT ON COLUMN "BNKPROJECT"."CHATMESSAGE"."ISREAD" IS '1 : true, 0 : false';
   COMMENT ON TABLE "BNKPROJECT"."CHATMESSAGE"  IS '채팅 세션의 개별 메시지 데이터.
송신자 구분(USER/CONSULTANT) 포함.';
--------------------------------------------------------
--  DDL for Table CHATSESSION
--------------------------------------------------------

  CREATE TABLE "BNKPROJECT"."CHATSESSION" 
   (	"SESSIONID" NUMBER, 
	"USERID" NUMBER, 
	"CONSULTANTID" NUMBER, 
	"INQUIRYTYPE" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"CREATEDAT" DATE DEFAULT SYSDATE, 
	"UPDATEDAT" DATE, 
	"PRIORITYSCORE" NUMBER(38,0), 
	"WAITSTARTTIME" DATE, 
	"CHATSTARTTIME" DATE, 
	"CHATENDTIME" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BNKPROJECT"."CHATSESSION"."SESSIONID" IS '세션 ID (PK)';
   COMMENT ON COLUMN "BNKPROJECT"."CHATSESSION"."USERID" IS '사용자 ID (FK)';
   COMMENT ON COLUMN "BNKPROJECT"."CHATSESSION"."CONSULTANTID" IS '상담원 ID (FK)';
   COMMENT ON COLUMN "BNKPROJECT"."CHATSESSION"."INQUIRYTYPE" IS '문의 유형';
   COMMENT ON COLUMN "BNKPROJECT"."CHATSESSION"."STATUS" IS '세션 상태 (WAITING, COMPLETE 등)';
   COMMENT ON COLUMN "BNKPROJECT"."CHATSESSION"."CREATEDAT" IS '생성일';
   COMMENT ON COLUMN "BNKPROJECT"."CHATSESSION"."UPDATEDAT" IS '수정일';
   COMMENT ON COLUMN "BNKPROJECT"."CHATSESSION"."PRIORITYSCORE" IS '대기순위';
   COMMENT ON COLUMN "BNKPROJECT"."CHATSESSION"."WAITSTARTTIME" IS '대기시작시간';
   COMMENT ON TABLE "BNKPROJECT"."CHATSESSION"  IS '사용자와 상담원 간 채팅 세션 내역.
문의유형, 상태, 연결 시간 기록.';
--------------------------------------------------------
--  DDL for Table CODEDETAIL
--------------------------------------------------------

  CREATE TABLE "BNKPROJECT"."CODEDETAIL" 
   (	"GROUPCODE" VARCHAR2(10 BYTE), 
	"CODE" VARCHAR2(10 BYTE), 
	"CODENAME" VARCHAR2(50 BYTE), 
	"USEYN" CHAR(1 BYTE) DEFAULT 'Y', 
	"CREATEDAT" DATE DEFAULT SYSDATE, 
	"UPDATEDAT" DATE, 
	"STATUS" CHAR(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BNKPROJECT"."CODEDETAIL"."GROUPCODE" IS '상위 코드 그룹 식별자 (FK)';
   COMMENT ON COLUMN "BNKPROJECT"."CODEDETAIL"."CODE" IS '세부 코드 값';
   COMMENT ON COLUMN "BNKPROJECT"."CODEDETAIL"."CODENAME" IS '코드의 이름';
   COMMENT ON COLUMN "BNKPROJECT"."CODEDETAIL"."USEYN" IS '코드 사용 여부';
   COMMENT ON COLUMN "BNKPROJECT"."CODEDETAIL"."CREATEDAT" IS '생성일';
   COMMENT ON COLUMN "BNKPROJECT"."CODEDETAIL"."UPDATEDAT" IS '수정일';
   COMMENT ON COLUMN "BNKPROJECT"."CODEDETAIL"."STATUS" IS '사용 상태(Y/N)';
   COMMENT ON TABLE "BNKPROJECT"."CODEDETAIL"  IS '각 코드 그룹별 세부 항목을 저장하는 테이블.
예: (PROD_TYPE, ‘01’) → ‘예금’.';
--------------------------------------------------------
--  DDL for Table CODEMASTER
--------------------------------------------------------

  CREATE TABLE "BNKPROJECT"."CODEMASTER" 
   (	"GROUPCODE" VARCHAR2(10 BYTE), 
	"GROUPNAME" VARCHAR2(50 BYTE), 
	"CREATEDAT" DATE DEFAULT SYSDATE, 
	"UPDATEDAT" DATE, 
	"STATUS" CHAR(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BNKPROJECT"."CODEMASTER"."GROUPCODE" IS '코드 그룹 식별자 (PK)';
   COMMENT ON COLUMN "BNKPROJECT"."CODEMASTER"."GROUPNAME" IS '코드 그룹명 (ex: 상품유형, 권한유형 등)';
   COMMENT ON COLUMN "BNKPROJECT"."CODEMASTER"."CREATEDAT" IS '생성일';
   COMMENT ON COLUMN "BNKPROJECT"."CODEMASTER"."UPDATEDAT" IS '수정일';
   COMMENT ON COLUMN "BNKPROJECT"."CODEMASTER"."STATUS" IS '사용 여부(Y/N)';
   COMMENT ON TABLE "BNKPROJECT"."CODEMASTER"  IS '시스템 내 코드 그룹(대분류)을 정의하는 테이블. 
예: 상품유형, 약관유형, 권한유형 등.';
--------------------------------------------------------
--  DDL for Table CONSULTANT
--------------------------------------------------------

  CREATE TABLE "BNKPROJECT"."CONSULTANT" 
   (	"CONSULTANTID" NUMBER, 
	"CONSULTANTNAME" VARCHAR2(100 BYTE), 
	"SPECIALTY" VARCHAR2(100 BYTE), 
	"STATUS" CHAR(1 BYTE) DEFAULT 'Y', 
	"CREATEDAT" DATE DEFAULT SYSDATE, 
	"UPDATEDAT" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BNKPROJECT"."CONSULTANT"."CONSULTANTID" IS '상담원 ID (PK)';
   COMMENT ON COLUMN "BNKPROJECT"."CONSULTANT"."CONSULTANTNAME" IS '상담원명';
   COMMENT ON COLUMN "BNKPROJECT"."CONSULTANT"."SPECIALTY" IS '전문 분야';
   COMMENT ON COLUMN "BNKPROJECT"."CONSULTANT"."STATUS" IS '활동 상태(Y/N)';
   COMMENT ON COLUMN "BNKPROJECT"."CONSULTANT"."CREATEDAT" IS '생성일';
   COMMENT ON COLUMN "BNKPROJECT"."CONSULTANT"."UPDATEDAT" IS '수정일';
   COMMENT ON TABLE "BNKPROJECT"."CONSULTANT"  IS '상담 직원(챗봇/상담사) 정보 관리.
상태(대기/상담중/오프라인) 표시.';
--------------------------------------------------------
--  DDL for Table CS
--------------------------------------------------------

  CREATE TABLE "BNKPROJECT"."CS" 
   (	"CSNO" NUMBER, 
	"USERID" NUMBER, 
	"CATEID" NUMBER, 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" CLOB, 
	"STATUS" CHAR(1 BYTE) DEFAULT 'Y', 
	"CREATEDAT" DATE DEFAULT SYSDATE, 
	"UPDATEDAT" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("CONTENT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

   COMMENT ON COLUMN "BNKPROJECT"."CS"."CSNO" IS '게시글 ID (PK)';
   COMMENT ON COLUMN "BNKPROJECT"."CS"."USERID" IS '작성자 ID (FK)';
   COMMENT ON COLUMN "BNKPROJECT"."CS"."CATEID" IS '카테고리 ID (FK)';
   COMMENT ON COLUMN "BNKPROJECT"."CS"."TITLE" IS '제목';
   COMMENT ON COLUMN "BNKPROJECT"."CS"."CONTENT" IS '본문';
   COMMENT ON COLUMN "BNKPROJECT"."CS"."STATUS" IS '게시글 상태(Y: 활성, N: 비활성 등)';
   COMMENT ON COLUMN "BNKPROJECT"."CS"."CREATEDAT" IS '생성일';
   COMMENT ON COLUMN "BNKPROJECT"."CS"."UPDATEDAT" IS '수정일';
   COMMENT ON TABLE "BNKPROJECT"."CS"  IS '고객센터 문의 게시글.
제목·내용·작성자·분류를 저장하고 답변과 연동.';
--------------------------------------------------------
--  DDL for Table CSCATE
--------------------------------------------------------

  CREATE TABLE "BNKPROJECT"."CSCATE" 
   (	"CATEID" NUMBER, 
	"CATENAME" VARCHAR2(100 BYTE), 
	"CREATEDAT" DATE DEFAULT SYSDATE, 
	"UPDATEDAT" DATE, 
	"STATUS" CHAR(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BNKPROJECT"."CSCATE"."CATEID" IS 'CS 카테고리 ID (PK)';
   COMMENT ON COLUMN "BNKPROJECT"."CSCATE"."CATENAME" IS '카테고리명';
   COMMENT ON COLUMN "BNKPROJECT"."CSCATE"."CREATEDAT" IS '생성일';
   COMMENT ON COLUMN "BNKPROJECT"."CSCATE"."UPDATEDAT" IS '수정일';
   COMMENT ON COLUMN "BNKPROJECT"."CSCATE"."STATUS" IS '사용 상태(Y/N)';
   COMMENT ON TABLE "BNKPROJECT"."CSCATE"  IS '고객센터 문의 분류(1차, 2차 카테고리 등)를 관리.';
--------------------------------------------------------
--  DDL for Table DAILY_QUEST
--------------------------------------------------------

  CREATE TABLE "BNKPROJECT"."DAILY_QUEST" 
   (	"QUEST_ID" NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"COMPLETED_COUNT" NUMBER(10,0), 
	"QUEST_DATE" DATE, 
	"QUIZ_IDS_JSON" CLOB, 
	"USER_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("QUIZ_IDS_JSON") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table EMAILCOUNSEL
--------------------------------------------------------

  CREATE TABLE "BNKPROJECT"."EMAILCOUNSEL" 
   (	"ECOUNSELID" NUMBER, 
	"USERID" NUMBER, 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" CLOB, 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'WAITING', 
	"CREATEDAT" DATE DEFAULT SYSDATE, 
	"UPDATEDAT" DATE, 
	"RESPONSE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("CONTENT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

   COMMENT ON COLUMN "BNKPROJECT"."EMAILCOUNSEL"."ECOUNSELID" IS '문의 식별자 (PK)';
   COMMENT ON COLUMN "BNKPROJECT"."EMAILCOUNSEL"."USERID" IS '문의자 ID (FK)';
   COMMENT ON COLUMN "BNKPROJECT"."EMAILCOUNSEL"."TITLE" IS '제목';
   COMMENT ON COLUMN "BNKPROJECT"."EMAILCOUNSEL"."CONTENT" IS '본문';
   COMMENT ON COLUMN "BNKPROJECT"."EMAILCOUNSEL"."STATUS" IS '상태(WAITING/COMPLETE 등)';
   COMMENT ON COLUMN "BNKPROJECT"."EMAILCOUNSEL"."CREATEDAT" IS '생성일';
   COMMENT ON COLUMN "BNKPROJECT"."EMAILCOUNSEL"."UPDATEDAT" IS '수정일';
   COMMENT ON TABLE "BNKPROJECT"."EMAILCOUNSEL"  IS '이메일 상담 내역 관리.
사용자 문의 제목·내용·처리상태를 저장.';
--------------------------------------------------------
--  DDL for Table FAQ
--------------------------------------------------------

  CREATE TABLE "BNKPROJECT"."FAQ" 
   (	"FAQID" NUMBER, 
	"GROUPCODE" VARCHAR2(255 CHAR), 
	"FAQCATEGORY" VARCHAR2(255 CHAR), 
	"QUESTION" VARCHAR2(255 CHAR), 
	"ANSWER" CLOB, 
	"CREATEDAT" DATE DEFAULT SYSDATE, 
	"UPDATEDAT" DATE, 
	"STATUS" VARCHAR2(255 CHAR) DEFAULT 'Y'
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("ANSWER") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

   COMMENT ON COLUMN "BNKPROJECT"."FAQ"."FAQID" IS 'FAQ 식별자 (PK)';
   COMMENT ON COLUMN "BNKPROJECT"."FAQ"."GROUPCODE" IS 'FAQ 유형 코드 (FK)';
   COMMENT ON COLUMN "BNKPROJECT"."FAQ"."FAQCATEGORY" IS 'FAQ 유형 코드 (FK)';
   COMMENT ON COLUMN "BNKPROJECT"."FAQ"."QUESTION" IS '질문';
   COMMENT ON COLUMN "BNKPROJECT"."FAQ"."ANSWER" IS '답변 내용';
   COMMENT ON COLUMN "BNKPROJECT"."FAQ"."CREATEDAT" IS '생성일';
   COMMENT ON COLUMN "BNKPROJECT"."FAQ"."UPDATEDAT" IS '수정일';
   COMMENT ON COLUMN "BNKPROJECT"."FAQ"."STATUS" IS '사용 상태(Y/N)';
   COMMENT ON TABLE "BNKPROJECT"."FAQ"  IS '자주 묻는 질문(FAQ)을 유형별로 관리.
codeDetail의 FAQ 카테고리 코드와 연결.';
--------------------------------------------------------
--  DDL for Table HIRE
--------------------------------------------------------

  CREATE TABLE "BNKPROJECT"."HIRE" 
   (	"HIRENO" NUMBER, 
	"DEPARTMENT" VARCHAR2(100 BYTE), 
	"HIRETITLE" VARCHAR2(200 BYTE), 
	"HIRESTATUS" VARCHAR2(20 BYTE), 
	"CREATEDAT" DATE DEFAULT SYSDATE, 
	"UPDATEDAT" DATE, 
	"STATUS" CHAR(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BNKPROJECT"."HIRE"."HIRENO" IS '공고 ID (PK)';
   COMMENT ON COLUMN "BNKPROJECT"."HIRE"."DEPARTMENT" IS '모집 부서';
   COMMENT ON COLUMN "BNKPROJECT"."HIRE"."HIRETITLE" IS '공고 제목';
   COMMENT ON COLUMN "BNKPROJECT"."HIRE"."HIRESTATUS" IS '상태(모집중, 마감 등)';
   COMMENT ON COLUMN "BNKPROJECT"."HIRE"."CREATEDAT" IS '생성일';
   COMMENT ON COLUMN "BNKPROJECT"."HIRE"."UPDATEDAT" IS '수정일';
   COMMENT ON COLUMN "BNKPROJECT"."HIRE"."STATUS" IS '활성 여부(Y/N)';
   COMMENT ON TABLE "BNKPROJECT"."HIRE"  IS '인재채용 공고 관리.
부서, 제목, 상태, 모집기간 등 채용 정보를 저장.';
--------------------------------------------------------
--  DDL for Table LOGACTIVITY
--------------------------------------------------------

  CREATE TABLE "BNKPROJECT"."LOGACTIVITY" 
   (	"LOGID" NUMBER, 
	"USERID" NUMBER, 
	"ADMINID" NUMBER, 
	"ACTIONTYPE" VARCHAR2(50 BYTE), 
	"IPADDRESS" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(500 BYTE), 
	"CREATEDAT" DATE DEFAULT SYSDATE, 
	"UPDATEDAT" DATE, 
	"STATUS" CHAR(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BNKPROJECT"."LOGACTIVITY"."LOGID" IS '로그 ID (PK)';
   COMMENT ON COLUMN "BNKPROJECT"."LOGACTIVITY"."USERID" IS '사용자 ID (FK)';
   COMMENT ON COLUMN "BNKPROJECT"."LOGACTIVITY"."ADMINID" IS '관리자 ID (FK)';
   COMMENT ON COLUMN "BNKPROJECT"."LOGACTIVITY"."ACTIONTYPE" IS '활동 유형 (VIEW, CREATE 등)';
   COMMENT ON COLUMN "BNKPROJECT"."LOGACTIVITY"."IPADDRESS" IS '접속 IP';
   COMMENT ON COLUMN "BNKPROJECT"."LOGACTIVITY"."DESCRIPTION" IS '상세설명';
   COMMENT ON COLUMN "BNKPROJECT"."LOGACTIVITY"."CREATEDAT" IS '생성일';
   COMMENT ON COLUMN "BNKPROJECT"."LOGACTIVITY"."UPDATEDAT" IS '수정일';
   COMMENT ON COLUMN "BNKPROJECT"."LOGACTIVITY"."STATUS" IS '상태(Y/N)';
   COMMENT ON TABLE "BNKPROJECT"."LOGACTIVITY"  IS '사용자/관리자 활동 기록 로그.
IP, 행동유형, 설명 등을 저장하여 감사용으로 활용.';
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "BNKPROJECT"."PRODUCT" 
   (	"PRODUCTNO" NUMBER, 
	"PRODUCTNAME" VARCHAR2(200 BYTE), 
	"PRODUCTTYPE" VARCHAR2(10 BYTE), 
	"CATEGORYID" NUMBER, 
	"DESCRIPTION" CLOB, 
	"BASERATE" NUMBER(5,2), 
	"MATURITYRATE" NUMBER(5,2), 
	"EARLYTERMINATERATE" NUMBER(5,2), 
	"MONTHLYAMOUNT" NUMBER(15,2), 
	"SAVINGTERM" NUMBER(3,0), 
	"DEPOSITAMOUNT" NUMBER(15,2), 
	"INTERESTMETHOD" VARCHAR2(50 BYTE), 
	"PAYCYCLE" VARCHAR2(50 BYTE), 
	"ENDDATE" DATE, 
	"ADMINID" NUMBER, 
	"CREATEDAT" DATE DEFAULT SYSDATE, 
	"UPDATEDAT" DATE, 
	"STATUS" CHAR(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("DESCRIPTION") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

   COMMENT ON COLUMN "BNKPROJECT"."PRODUCT"."PRODUCTNO" IS '상품번호';
   COMMENT ON COLUMN "BNKPROJECT"."PRODUCT"."PRODUCTNAME" IS '상품이름';
   COMMENT ON COLUMN "BNKPROJECT"."PRODUCT"."PRODUCTTYPE" IS '상품타입코드(예: 예금 1, 적금 2)';
   COMMENT ON COLUMN "BNKPROJECT"."PRODUCT"."CATEGORYID" IS '상품카테고리 ID(FK)';
   COMMENT ON COLUMN "BNKPROJECT"."PRODUCT"."DESCRIPTION" IS '상품설명';
   COMMENT ON COLUMN "BNKPROJECT"."PRODUCT"."BASERATE" IS '기준금리(%)';
   COMMENT ON COLUMN "BNKPROJECT"."PRODUCT"."MATURITYRATE" IS '만기 적용 이율(%)';
   COMMENT ON COLUMN "BNKPROJECT"."PRODUCT"."EARLYTERMINATERATE" IS '중도해지 이율(%)';
   COMMENT ON COLUMN "BNKPROJECT"."PRODUCT"."MONTHLYAMOUNT" IS '월 납입액(적금 전용)';
   COMMENT ON COLUMN "BNKPROJECT"."PRODUCT"."SAVINGTERM" IS '적립기간(개월, 적금 전용)';
   COMMENT ON COLUMN "BNKPROJECT"."PRODUCT"."DEPOSITAMOUNT" IS '예치금(예금 전용), 일시 예치 금액';
   COMMENT ON COLUMN "BNKPROJECT"."PRODUCT"."INTERESTMETHOD" IS '이자 계산 방식(단리/복리/만기지금/월지급 등)';
   COMMENT ON COLUMN "BNKPROJECT"."PRODUCT"."PAYCYCLE" IS '납입 주기';
   COMMENT ON COLUMN "BNKPROJECT"."PRODUCT"."ENDDATE" IS '상품 종료일';
   COMMENT ON COLUMN "BNKPROJECT"."PRODUCT"."ADMINID" IS '관리자ID(FK)';
   COMMENT ON COLUMN "BNKPROJECT"."PRODUCT"."CREATEDAT" IS '상품정보 DB 생성일';
   COMMENT ON COLUMN "BNKPROJECT"."PRODUCT"."UPDATEDAT" IS '상품정보 최종 수정일';
   COMMENT ON COLUMN "BNKPROJECT"."PRODUCT"."STATUS" IS '상품상태(Y/N): 현재 판매중인지 여부';
   COMMENT ON TABLE "BNKPROJECT"."PRODUCT"  IS '실제 금융 상품 정보 관리: 예금/적금 등 모든 상품의 금리, 납입, 기간, 상태를 통합 저장';
--------------------------------------------------------
--  DDL for Table QUIZ
--------------------------------------------------------

  CREATE TABLE "BNKPROJECT"."QUIZ" 
   (	"QUIZ_ID" NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CATEGORY" VARCHAR2(50 CHAR), 
	"CORRECT_ANSWER" NUMBER(10,0), 
	"CREATED_DATE" TIMESTAMP (6), 
	"DIFFICULTY" NUMBER(10,0), 
	"EXPLANATION" VARCHAR2(1000 CHAR), 
	"OPTIONS_JSON" CLOB, 
	"QUESTION" VARCHAR2(500 CHAR), 
	"UPDATED_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("OPTIONS_JSON") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table SECURELOG
--------------------------------------------------------

  CREATE TABLE "BNKPROJECT"."SECURELOG" 
   (	"LOGID" NUMBER, 
	"ADMINID" NUMBER, 
	"LOGDATETIME" DATE DEFAULT SYSDATE, 
	"EVENTTYPE" VARCHAR2(50 BYTE), 
	"DETAILCONTENT" CLOB, 
	"CREATEDAT" DATE DEFAULT SYSDATE, 
	"UPDATEDAT" DATE, 
	"STATUS" CHAR(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("DETAILCONTENT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

   COMMENT ON COLUMN "BNKPROJECT"."SECURELOG"."LOGID" IS '로그 식별자 (PK)';
   COMMENT ON COLUMN "BNKPROJECT"."SECURELOG"."ADMINID" IS '관리자 ID (FK)';
   COMMENT ON COLUMN "BNKPROJECT"."SECURELOG"."LOGDATETIME" IS '이벤트 발생 시각';
   COMMENT ON COLUMN "BNKPROJECT"."SECURELOG"."EVENTTYPE" IS '이벤트 유형 (LOGIN, DELETE 등)';
   COMMENT ON COLUMN "BNKPROJECT"."SECURELOG"."DETAILCONTENT" IS '상세 내용';
   COMMENT ON COLUMN "BNKPROJECT"."SECURELOG"."CREATEDAT" IS '생성일';
   COMMENT ON COLUMN "BNKPROJECT"."SECURELOG"."UPDATEDAT" IS '수정일';
   COMMENT ON COLUMN "BNKPROJECT"."SECURELOG"."STATUS" IS '로그 활성 상태';
   COMMENT ON TABLE "BNKPROJECT"."SECURELOG"  IS '관리자 로그인 및 시스템 접근, 중요 변경 내역을 기록하는 보안 로그.';
--------------------------------------------------------
--  DDL for Table TERM
--------------------------------------------------------

  CREATE TABLE "BNKPROJECT"."TERM" 
   (	"TERMNO" NUMBER, 
	"GROUPCODE" VARCHAR2(10 BYTE), 
	"TERMTYPE" VARCHAR2(10 BYTE), 
	"TERMVERSION" VARCHAR2(10 BYTE), 
	"TERMTITLE" VARCHAR2(200 BYTE), 
	"TERMCONTENT" CLOB, 
	"APPLYDATE" DATE, 
	"CREATEDAT" DATE DEFAULT SYSDATE, 
	"UPDATEDAT" DATE, 
	"STATUS" CHAR(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("TERMCONTENT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

   COMMENT ON COLUMN "BNKPROJECT"."TERM"."TERMNO" IS '약관 번호 (PK)';
   COMMENT ON COLUMN "BNKPROJECT"."TERM"."GROUPCODE" IS '약관 유형 그룹';
   COMMENT ON COLUMN "BNKPROJECT"."TERM"."TERMTYPE" IS '약관 유형 세부 코드';
   COMMENT ON COLUMN "BNKPROJECT"."TERM"."TERMVERSION" IS '약관 버전';
   COMMENT ON COLUMN "BNKPROJECT"."TERM"."TERMTITLE" IS '약관 제목';
   COMMENT ON COLUMN "BNKPROJECT"."TERM"."TERMCONTENT" IS '약관 내용';
   COMMENT ON COLUMN "BNKPROJECT"."TERM"."APPLYDATE" IS '적용일';
   COMMENT ON COLUMN "BNKPROJECT"."TERM"."CREATEDAT" IS '생성일';
   COMMENT ON COLUMN "BNKPROJECT"."TERM"."UPDATEDAT" IS '수정일';
   COMMENT ON COLUMN "BNKPROJECT"."TERM"."STATUS" IS '상태(Y/N)';
   COMMENT ON TABLE "BNKPROJECT"."TERM"  IS '각 약관의 버전·적용일·내용을 관리.
codeDetail을 참조해 약관유형(TERM_TYPE)을 구분.';
--------------------------------------------------------
--  DDL for Table USERPRODUCT
--------------------------------------------------------

  CREATE TABLE "BNKPROJECT"."USERPRODUCT" 
   (	"USERID" NUMBER, 
	"PRODUCTNO" NUMBER, 
	"STARTDATE" DATE, 
	"STATUS" CHAR(1 BYTE) DEFAULT 'A', 
	"CREATEDAT" DATE DEFAULT SYSDATE, 
	"UPDATEDAT" DATE, 
	"ENDDATE" DATE, 
	"APPLYRATE" NUMBER(5,2), 
	"CONTRACTTERM" NUMBER(3,0), 
	"PRINCIPALAMOUNT" NUMBER(15,2), 
	"EXPECTEDENDDATE" DATE, 
	"CONTRACTEARLYRATE" NUMBER(5,2), 
	"ACCOUNTPASSWORD" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BNKPROJECT"."USERPRODUCT"."USERID" IS '회원ID (FK)';
   COMMENT ON COLUMN "BNKPROJECT"."USERPRODUCT"."PRODUCTNO" IS '상품 ID (FK)';
   COMMENT ON COLUMN "BNKPROJECT"."USERPRODUCT"."STARTDATE" IS '상품가입일';
   COMMENT ON COLUMN "BNKPROJECT"."USERPRODUCT"."STATUS" IS '상태 (A:유효/N:해지 등)';
   COMMENT ON COLUMN "BNKPROJECT"."USERPRODUCT"."CREATEDAT" IS '생성일';
   COMMENT ON COLUMN "BNKPROJECT"."USERPRODUCT"."UPDATEDAT" IS '고객상품가입정보 업데이트용';
   COMMENT ON COLUMN "BNKPROJECT"."USERPRODUCT"."ENDDATE" IS '상품해지(종료)일';
   COMMENT ON COLUMN "BNKPROJECT"."USERPRODUCT"."APPLYRATE" IS '가입시 최종 적용 이율(%)';
   COMMENT ON COLUMN "BNKPROJECT"."USERPRODUCT"."CONTRACTTERM" IS '계약기간(개월): 만기일 계산 및 계약 유효성 검증용. 상품의 가입기간과 다름.';
   COMMENT ON COLUMN "BNKPROJECT"."USERPRODUCT"."PRINCIPALAMOUNT" IS '가입 원금/최초납입액 : 이자계산 기준금액';
   COMMENT ON COLUMN "BNKPROJECT"."USERPRODUCT"."EXPECTEDENDDATE" IS '예상 만기일: STARTDATE + CONTRACTTERM을 기준으로 계산';
   COMMENT ON COLUMN "BNKPROJECT"."USERPRODUCT"."CONTRACTEARLYRATE" IS '고객별 확정된 중도해지 이율(계약시점 값 복사).';
   COMMENT ON COLUMN "BNKPROJECT"."USERPRODUCT"."ACCOUNTPASSWORD" IS '회원 계좌 비밀번호(FK)';
   COMMENT ON TABLE "BNKPROJECT"."USERPRODUCT"  IS '사용자가 가입한 금융상품 내역을 관리. 동일 상품 중복가입을 방지함.';
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "BNKPROJECT"."USERS" 
   (	"USERNO" NUMBER, 
	"USERNAME" VARCHAR2(255 BYTE), 
	"USERID" VARCHAR2(255 BYTE), 
	"USERPW" VARCHAR2(255 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"HP" VARCHAR2(255 BYTE), 
	"ZIP" VARCHAR2(20 BYTE), 
	"ADDR1" VARCHAR2(200 BYTE), 
	"ADDR2" VARCHAR2(200 BYTE), 
	"ROLE" VARCHAR2(20 BYTE) DEFAULT 'USER', 
	"REGDATE" DATE DEFAULT SYSDATE, 
	"CREATEDAT" DATE DEFAULT SYSDATE, 
	"UPDATEDAT" DATE, 
	"STATUS" CHAR(1 BYTE) DEFAULT 'A', 
	"ACCOUNTPASSWORD" VARCHAR2(255 BYTE), 
	"RRN" VARCHAR2(255 BYTE), 
	"USERPRIORITY" VARCHAR2(20 BYTE) DEFAULT 'BASIC'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BNKPROJECT"."USERS"."USERNO" IS '사용자 고유번호 (PK)';
   COMMENT ON COLUMN "BNKPROJECT"."USERS"."USERNAME" IS '사용자 이름';
   COMMENT ON COLUMN "BNKPROJECT"."USERS"."USERID" IS '로그인용 아이디';
   COMMENT ON COLUMN "BNKPROJECT"."USERS"."USERPW" IS '암호화된 비밀번호';
   COMMENT ON COLUMN "BNKPROJECT"."USERS"."EMAIL" IS '이메일';
   COMMENT ON COLUMN "BNKPROJECT"."USERS"."HP" IS '휴대폰 번호';
   COMMENT ON COLUMN "BNKPROJECT"."USERS"."ZIP" IS '우편번호';
   COMMENT ON COLUMN "BNKPROJECT"."USERS"."ADDR1" IS '기본 주소';
   COMMENT ON COLUMN "BNKPROJECT"."USERS"."ADDR2" IS '상세 주소';
   COMMENT ON COLUMN "BNKPROJECT"."USERS"."ROLE" IS '권한';
   COMMENT ON COLUMN "BNKPROJECT"."USERS"."REGDATE" IS '회원 가입일';
   COMMENT ON COLUMN "BNKPROJECT"."USERS"."CREATEDAT" IS '생성일(로그성 기록, DB 입력 날짜)';
   COMMENT ON COLUMN "BNKPROJECT"."USERS"."UPDATEDAT" IS '수정일';
   COMMENT ON COLUMN "BNKPROJECT"."USERS"."STATUS" IS '상태';
   COMMENT ON COLUMN "BNKPROJECT"."USERS"."ACCOUNTPASSWORD" IS '출금계좌 비밀번호 4자리';
   COMMENT ON COLUMN "BNKPROJECT"."USERS"."RRN" IS '주민등록번호';
   COMMENT ON COLUMN "BNKPROJECT"."USERS"."USERPRIORITY" IS '고객등급';
   COMMENT ON TABLE "BNKPROJECT"."USERS"  IS '사용자 정보 관리 테이블.
로그인 ID, 이름, 연락처, 권한, 가입일 등 핵심 회원정보 저장.';
--------------------------------------------------------
--  DDL for Table USER_LEVEL
--------------------------------------------------------

  CREATE TABLE "BNKPROJECT"."USER_LEVEL" 
   (	"LEVEL_ID" NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CREATED_DATE" TIMESTAMP (6), 
	"CURRENT_LEVEL" NUMBER(10,0), 
	"INTEREST_BONUS" NUMBER(3,2), 
	"TIER" VARCHAR2(50 CHAR), 
	"TOTAL_POINTS" NUMBER(10,0), 
	"UPDATED_DATE" TIMESTAMP (6), 
	"USER_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER_QUIZ_PROGRESS
--------------------------------------------------------

  CREATE TABLE "BNKPROJECT"."USER_QUIZ_PROGRESS" 
   (	"PROGRESS_ID" NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"EARNED_POINTS" NUMBER(10,0), 
	"IS_CORRECT" NUMBER(1,0), 
	"SUBMITTED_AT" TIMESTAMP (6), 
	"USER_ID" NUMBER(19,0), 
	"QUIZ_ID" NUMBER(19,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into BNKPROJECT.ACCOUNT
SET DEFINE OFF;
Insert into BNKPROJECT.ACCOUNT (ACCOUNTNO,USERID,BALANCE,CREATEDAT,UPDATEDAT,STATUS) values (1172356740403,271044864,5000000,to_date('25/11/14','RR/MM/DD'),null,'Y');
REM INSERTING into BNKPROJECT.ADMIN
SET DEFINE OFF;
Insert into BNKPROJECT.ADMIN (ADMINID,ADMINNAME,LOGINID,PASSWORD,ADMINROLE,CREATEDAT,UPDATEDAT,STATUS) values (1,'서정로그인테스트용','a1234','$2a$10$bdqZh8t7XYz4zzCZR5TKmOftOzZag.687t2M/1Ey0iDugVg4iTGh2','ADMIN',to_date('25/11/13','RR/MM/DD'),null,'Y');
REM INSERTING into BNKPROJECT.BANNER
SET DEFINE OFF;
REM INSERTING into BNKPROJECT.CATEGORY
SET DEFINE OFF;
REM INSERTING into BNKPROJECT.CHATMESSAGE
SET DEFINE OFF;
REM INSERTING into BNKPROJECT.CHATSESSION
SET DEFINE OFF;
REM INSERTING into BNKPROJECT.CODEDETAIL
SET DEFINE OFF;
Insert into BNKPROJECT.CODEDETAIL (GROUPCODE,CODE,CODENAME,USEYN,CREATEDAT,UPDATEDAT,STATUS) values ('TERM_TYPE','01','전자금융거래약관','Y',to_date('25/11/09','RR/MM/DD'),null,'Y');
Insert into BNKPROJECT.CODEDETAIL (GROUPCODE,CODE,CODENAME,USEYN,CREATEDAT,UPDATEDAT,STATUS) values ('TERM_TYPE','02','개인정보수집이용동의','Y',to_date('25/11/09','RR/MM/DD'),null,'Y');
Insert into BNKPROJECT.CODEDETAIL (GROUPCODE,CODE,CODENAME,USEYN,CREATEDAT,UPDATEDAT,STATUS) values ('TERM_TYPE','03','마케팅수신동의','Y',to_date('25/11/09','RR/MM/DD'),null,'Y');
Insert into BNKPROJECT.CODEDETAIL (GROUPCODE,CODE,CODENAME,USEYN,CREATEDAT,UPDATEDAT,STATUS) values ('PROD_TYPE','01','예금','Y',to_date('25/11/09','RR/MM/DD'),null,'Y');
Insert into BNKPROJECT.CODEDETAIL (GROUPCODE,CODE,CODENAME,USEYN,CREATEDAT,UPDATEDAT,STATUS) values ('PROD_TYPE','02','적금','Y',to_date('25/11/09','RR/MM/DD'),null,'Y');
Insert into BNKPROJECT.CODEDETAIL (GROUPCODE,CODE,CODENAME,USEYN,CREATEDAT,UPDATEDAT,STATUS) values ('FAQ_TYPE','01','계좌 관련','Y',to_date('25/11/09','RR/MM/DD'),null,'Y');
Insert into BNKPROJECT.CODEDETAIL (GROUPCODE,CODE,CODENAME,USEYN,CREATEDAT,UPDATEDAT,STATUS) values ('FAQ_TYPE','02','상품 문의','Y',to_date('25/11/09','RR/MM/DD'),null,'Y');
Insert into BNKPROJECT.CODEDETAIL (GROUPCODE,CODE,CODENAME,USEYN,CREATEDAT,UPDATEDAT,STATUS) values ('FAQ_TYPE','03','기타','Y',to_date('25/11/09','RR/MM/DD'),null,'Y');
REM INSERTING into BNKPROJECT.CODEMASTER
SET DEFINE OFF;
Insert into BNKPROJECT.CODEMASTER (GROUPCODE,GROUPNAME,CREATEDAT,UPDATEDAT,STATUS) values ('TERM_TYPE','약관유형',to_date('25/11/09','RR/MM/DD'),null,'Y');
Insert into BNKPROJECT.CODEMASTER (GROUPCODE,GROUPNAME,CREATEDAT,UPDATEDAT,STATUS) values ('PROD_TYPE','상품유형',to_date('25/11/09','RR/MM/DD'),null,'Y');
Insert into BNKPROJECT.CODEMASTER (GROUPCODE,GROUPNAME,CREATEDAT,UPDATEDAT,STATUS) values ('FAQ_TYPE','FAQ 카테고리',to_date('25/11/09','RR/MM/DD'),null,'Y');
Insert into BNKPROJECT.CODEMASTER (GROUPCODE,GROUPNAME,CREATEDAT,UPDATEDAT,STATUS) values ('ROLE_TYPE','권한유형',to_date('25/11/09','RR/MM/DD'),null,'Y');
REM INSERTING into BNKPROJECT.CONSULTANT
SET DEFINE OFF;
REM INSERTING into BNKPROJECT.CS
SET DEFINE OFF;
REM INSERTING into BNKPROJECT.CSCATE
SET DEFINE OFF;
REM INSERTING into BNKPROJECT.DAILY_QUEST
SET DEFINE OFF;
REM INSERTING into BNKPROJECT.EMAILCOUNSEL
SET DEFINE OFF;
REM INSERTING into BNKPROJECT.FAQ
SET DEFINE OFF;
REM INSERTING into BNKPROJECT.HIRE
SET DEFINE OFF;
REM INSERTING into BNKPROJECT.LOGACTIVITY
SET DEFINE OFF;
REM INSERTING into BNKPROJECT.PRODUCT
SET DEFINE OFF;
REM INSERTING into BNKPROJECT.QUIZ
SET DEFINE OFF;
Insert into BNKPROJECT.QUIZ (QUIZ_ID,CATEGORY,CORRECT_ANSWER,CREATED_DATE,DIFFICULTY,EXPLANATION,QUESTION,UPDATED_DATE) values (1,'FINANCE',1,to_timestamp('25/11/13 07:59:39.131760000','RR/MM/DD HH24:MI:SSXFF'),2,'�덇툑�먮낫�몃쾿�� 湲덉쑖湲곌����뚯궛�섍굅���곸뾽���뺤���寃쎌슦 �덇툑�먮� 蹂댄샇�섍린 �꾪빐 1�몃떦 理쒕� 5泥쒕쭔�먭퉴吏� 蹂댄샇�⑸땲��','�덇툑��蹂댄샇踰뺤뿉 �곕씪 1�몃떦 蹂댄샇�섎뒗 �덇툑 �쒕룄���쇰쭏�멸���',to_timestamp('25/11/13 07:59:39.131760000','RR/MM/DD HH24:MI:SSXFF'));
Insert into BNKPROJECT.QUIZ (QUIZ_ID,CATEGORY,CORRECT_ANSWER,CREATED_DATE,DIFFICULTY,EXPLANATION,QUESTION,UPDATED_DATE) values (2,'INVESTMENT',1,to_timestamp('25/11/13 07:59:39.144588000','RR/MM/DD HH24:MI:SSXFF'),3,'PER(Price Earnings Ratio)�� 二쇨�瑜�二쇰떦�쒖씠��EPS)�쇰줈 �섎늿 媛믪쑝濡� 二쇨�媛� 1二쇰떦 �섏씡��紐�諛곕줈 嫄곕옒�섎뒗吏�瑜��섑��낅땲��','二쇱떇 �ъ옄�먯꽌 PER(二쇨��섏씡鍮꾩쑉)���섎��섎뒗 寃껋�?',to_timestamp('25/11/13 07:59:39.144588000','RR/MM/DD HH24:MI:SSXFF'));
Insert into BNKPROJECT.QUIZ (QUIZ_ID,CATEGORY,CORRECT_ANSWER,CREATED_DATE,DIFFICULTY,EXPLANATION,QUESTION,UPDATED_DATE) values (3,'SAVINGS',1,to_timestamp('25/11/13 07:59:39.155795000','RR/MM/DD HH24:MI:SSXFF'),1,'�덇툑�� 紐⑸룉���쒕쾲��留↔린怨�留뚭린���먭툑怨��댁옄瑜�諛쏅뒗 寃껋씠硫� �곴툑�� 留ㅼ썡 �쇱젙 湲덉븸���섎늻���⑹엯�섎뒗 �곹뭹�낅땲��','�곴툑怨��덇툑��李⑥씠�먯� 臾댁뾿�멸���',to_timestamp('25/11/13 07:59:39.155795000','RR/MM/DD HH24:MI:SSXFF'));
Insert into BNKPROJECT.QUIZ (QUIZ_ID,CATEGORY,CORRECT_ANSWER,CREATED_DATE,DIFFICULTY,EXPLANATION,QUESTION,UPDATED_DATE) values (4,'CREDIT',2,to_timestamp('25/11/13 07:59:39.166270000','RR/MM/DD HH24:MI:SSXFF'),2,'�좎슜�먯닔����異쒓툑怨�移대뱶 ��湲덉쓣 �쒕븣 �⑸��섎㈃ �곸듅�⑸땲�� �곗껜���좎슜�먯닔 �섎씫��二쇱슂 �먯씤�낅땲��','�좎슜�먯닔瑜��щ━��諛⑸쾿�쇰줈 �щ컮瑜�寃껋�?',to_timestamp('25/11/13 07:59:39.166270000','RR/MM/DD HH24:MI:SSXFF'));
Insert into BNKPROJECT.QUIZ (QUIZ_ID,CATEGORY,CORRECT_ANSWER,CREATED_DATE,DIFFICULTY,EXPLANATION,QUESTION,UPDATED_DATE) values (5,'LOAN',0,to_timestamp('25/11/13 07:59:39.177366000','RR/MM/DD HH24:MI:SSXFF'),3,'LTV(Loan To Value)���대낫媛�移���鍮���異쒕퉬�⑤줈, 二쇳깮 媛�寃⑹쓽 70%源뚯� ��異쒕컺�����덈떎���섎��낅땲��','二쇳깮�대낫��異쒖쓽 LTV 鍮꾩쑉��70%�쇰뒗 寃껋쓽 �섎���',to_timestamp('25/11/13 07:59:39.177366000','RR/MM/DD HH24:MI:SSXFF'));
Insert into BNKPROJECT.QUIZ (QUIZ_ID,CATEGORY,CORRECT_ANSWER,CREATED_DATE,DIFFICULTY,EXPLANATION,QUESTION,UPDATED_DATE) values (6,'INVESTMENT',1,to_timestamp('25/11/13 07:59:39.188366000','RR/MM/DD HH24:MI:SSXFF'),2,'蹂듬━���댁옄���댁옄媛� 遺숇뒗 �④낵濡� �ъ옄 湲곌컙��湲몄닔濡�蹂듬━ �④낵媛� 而ㅼ쭛�덈떎.','蹂듬━ �④낵媛� 媛�����寃쎌슦��',to_timestamp('25/11/13 07:59:39.188366000','RR/MM/DD HH24:MI:SSXFF'));
Insert into BNKPROJECT.QUIZ (QUIZ_ID,CATEGORY,CORRECT_ANSWER,CREATED_DATE,DIFFICULTY,EXPLANATION,QUESTION,UPDATED_DATE) values (7,'INVESTMENT',1,to_timestamp('25/11/13 07:59:39.198857000','RR/MM/DD HH24:MI:SSXFF'),4,'湲덈━�� 梨꾧텒 媛�寃⑹� 諛섎�濡���吏곸엯�덈떎. 湲덈━媛� �ㅻⅤ硫�湲곗〈 梨꾧텒��媛�移섍� �⑥뼱吏�誘�濡�梨꾧텒 媛�寃⑹� �섎씫�⑸땲��','湲덈━媛� �곸듅�섎㈃ 梨꾧텒 媛�寃⑹� �대뼸寃��섎굹��',to_timestamp('25/11/13 07:59:39.198857000','RR/MM/DD HH24:MI:SSXFF'));
Insert into BNKPROJECT.QUIZ (QUIZ_ID,CATEGORY,CORRECT_ANSWER,CREATED_DATE,DIFFICULTY,EXPLANATION,QUESTION,UPDATED_DATE) values (8,'SAVINGS',1,to_timestamp('25/11/13 07:59:39.209995000','RR/MM/DD HH24:MI:SSXFF'),2,'�뺢린�덇툑��留뚭린 �꾩뿉 以묐룄�댁��섎㈃ �쎌젙��湲덈━蹂대떎 ��� 以묐룄�댁� 湲덈━媛� �곸슜�섏뼱 �댁옄 �먯떎��諛쒖깮�⑸땲��','�뺢린�덇툑��以묐룄�댁� ���대뼡 �먯떎��諛쒖깮�섎굹��',to_timestamp('25/11/13 07:59:39.209995000','RR/MM/DD HH24:MI:SSXFF'));
Insert into BNKPROJECT.QUIZ (QUIZ_ID,CATEGORY,CORRECT_ANSWER,CREATED_DATE,DIFFICULTY,EXPLANATION,QUESTION,UPDATED_DATE) values (9,'FINANCE',0,to_timestamp('25/11/13 07:59:39.222480000','RR/MM/DD HH24:MI:SSXFF'),3,'ISA 怨꾩쥖���ㅼ뼇��湲덉쑖�곹뭹���섎굹��怨꾩쥖濡�愿�由ы븷 ���덉쑝硫� �쇱젙 湲덉븸源뚯� 鍮꾧낵���쒗깮��諛쏆쓣 ���덉뒿�덈떎.','ISA(媛쒖씤醫낇빀�먯궛愿�由ш퀎醫���二쇱슂 �μ젏��?',to_timestamp('25/11/13 07:59:39.222480000','RR/MM/DD HH24:MI:SSXFF'));
Insert into BNKPROJECT.QUIZ (QUIZ_ID,CATEGORY,CORRECT_ANSWER,CREATED_DATE,DIFFICULTY,EXPLANATION,QUESTION,UPDATED_DATE) values (10,'CREDIT',2,to_timestamp('25/11/13 07:59:39.234386000','RR/MM/DD HH24:MI:SSXFF'),3,'由щ낵鍮숈� 移대뱶 ��湲덉쓣 遺꾪븷 �⑸��섎뒗 寃껋쑝濡� ��15~20%���믪� �댁옄媛� 遺�怨쇰릺���κ린�곸쑝濡���遺��댁씠 �⑸땲��','�좎슜移대뱶 由щ낵鍮숈쓽 �꾪뿕�깆�?',to_timestamp('25/11/13 07:59:39.234386000','RR/MM/DD HH24:MI:SSXFF'));
REM INSERTING into BNKPROJECT.SECURELOG
SET DEFINE OFF;
REM INSERTING into BNKPROJECT.TERM
SET DEFINE OFF;
REM INSERTING into BNKPROJECT.USERPRODUCT
SET DEFINE OFF;
REM INSERTING into BNKPROJECT.USERS
SET DEFINE OFF;
Insert into BNKPROJECT.USERS (USERNO,USERNAME,USERID,USERPW,EMAIL,HP,ZIP,ADDR1,ADDR2,ROLE,REGDATE,CREATEDAT,UPDATEDAT,STATUS,ACCOUNTPASSWORD,RRN,USERPRIORITY) values (271044864,'UwvOoDQVegRIz7SkTl7JLQ==','os3754','$2a$10$LZxkKmJlgrKLpK3Jbns2FObOm7cCXRTiaDlOiAvb8MKU2ISQJI47e','tS8ouP3Nk4X7kbSJOd5lPATK6DzJMsBPAuWKNWSUBVA=','PhHTdeMEVi/HDqyfmMKWlg==','13479','경기 성남시 분당구 서판교로 32','1동','USER',to_date('25/11/13','RR/MM/DD'),to_date('25/11/13','RR/MM/DD'),to_date('25/11/13','RR/MM/DD'),'A','$2a$10$uDymn5l4s33o6E6UVM6hwuwDOmTI4NBqZZ7fFgDOAbmDyNn4Hl7xu','NXriGcR0tQX/xCnnLuvO8TYwMeSQalW66Df4hc5Fpvg=','BASIC');
Insert into BNKPROJECT.USERS (USERNO,USERNAME,USERID,USERPW,EMAIL,HP,ZIP,ADDR1,ADDR2,ROLE,REGDATE,CREATEDAT,UPDATEDAT,STATUS,ACCOUNTPASSWORD,RRN,USERPRIORITY) values (231837262,'UwvOoDQVegRIz7SkTl7JLQ==','test','$2a$10$GPxoU72BdKLW8pGlBPxObeJjdb7Lz6fXHXhVL2hCpZhHcpm.Tt3VS','sl75vnQUN5P7D+fRdzMjB2n/of6EsPAtKmxIaHAgf40=','PhHTdeMEVi/HDqyfmMKWlg==','07766','서울 강서구 월정로28가길 13-19','2동','USER',to_date('25/11/13','RR/MM/DD'),to_date('25/11/13','RR/MM/DD'),to_date('25/11/13','RR/MM/DD'),'A','1','NXriGcR0tQX/xCnnLuvO8TYwMeSQalW66Df4hc5Fpvg=','BASIC');
REM INSERTING into BNKPROJECT.USER_LEVEL
SET DEFINE OFF;
Insert into BNKPROJECT.USER_LEVEL (LEVEL_ID,CREATED_DATE,CURRENT_LEVEL,INTEREST_BONUS,TIER,TOTAL_POINTS,UPDATED_DATE,USER_ID) values (1,to_timestamp('25/11/13 07:59:39.254042000','RR/MM/DD HH24:MI:SSXFF'),1,0,'Rookie',0,to_timestamp('25/11/13 07:59:39.254042000','RR/MM/DD HH24:MI:SSXFF'),1);
REM INSERTING into BNKPROJECT.USER_QUIZ_PROGRESS
SET DEFINE OFF;
