--------------------------------------------------------
-- 작성자: 진원
-- 작성일: 2025-11-20
-- 설명: 관리자 보안 설정 테이블 생성 및 초기 데이터
--------------------------------------------------------

-- 테이블 생성
CREATE TABLE "BNKPROJECT"."SECURITYSETTINGS"
(
    "SETTINGKEY"   VARCHAR2(50 BYTE) NOT NULL,
    "SETTINGVALUE" VARCHAR2(500 BYTE),
    "SETTINGTYPE"  VARCHAR2(20 BYTE) DEFAULT 'STRING',
    "SETTINGDESC"  VARCHAR2(200 BYTE),
    "UPDATEDDATE"  DATE DEFAULT SYSDATE,
    "UPDATEDBY"    VARCHAR2(50 BYTE),
    "USEYN"        CHAR(1 BYTE) DEFAULT 'Y',
      CONSTRAINT "SECURITYSETTINGS_PK" PRIMARY KEY ("SETTINGKEY")
  );

-- 컬럼 코멘트
COMMENT ON COLUMN "BNKPROJECT"."SECURITYSETTINGS"."SETTINGKEY" IS '보안 설정 키 (PK)';
  COMMENT ON COLUMN "BNKPROJECT"."SECURITYSETTINGS"."SETTINGVALUE" IS '설정 값';
  COMMENT ON COLUMN "BNKPROJECT"."SECURITYSETTINGS"."SETTINGTYPE" IS '데이터 타입 (NUMBER, STRING, DATE, BOOLEAN)';
  COMMENT ON COLUMN "BNKPROJECT"."SECURITYSETTINGS"."SETTINGDESC" IS '설정 설명';
  COMMENT ON COLUMN "BNKPROJECT"."SECURITYSETTINGS"."UPDATEDDATE" IS '최종 수정일';
  COMMENT ON COLUMN "BNKPROJECT"."SECURITYSETTINGS"."UPDATEDBY" IS '최종 수정자';
  COMMENT ON COLUMN "BNKPROJECT"."SECURITYSETTINGS"."USEYN" IS '사용 여부 (Y/N)';
  COMMENT ON TABLE "BNKPROJECT"."SECURITYSETTINGS" IS '관리자 보안 설정 정보';

  -- 초기 데이터 삽입
Insert into BNKPROJECT.SECURITYSETTINGS (SETTINGKEY, SETTINGVALUE, SETTINGTYPE, SETTINGDESC, UPDATEDBY, USEYN)
values ('PASSWORD_MIN_LENGTH', '8', 'NUMBER', '관리자 비밀번호 최소 길이', 'SYSTEM', 'Y');

Insert into BNKPROJECT.SECURITYSETTINGS (SETTINGKEY, SETTINGVALUE, SETTINGTYPE, SETTINGDESC, UPDATEDBY, USEYN)
values ('LOGIN_FAIL_LIMIT', '5', 'NUMBER', '로그인 실패 횟수 제한 (계정 잠금)', 'SYSTEM', 'Y');

Insert into BNKPROJECT.SECURITYSETTINGS (SETTINGKEY, SETTINGVALUE, SETTINGTYPE, SETTINGDESC, UPDATEDBY, USEYN)
values ('SESSION_TIMEOUT', '30', 'NUMBER', '세션 타임아웃 (분)', 'SYSTEM', 'Y');

Insert into BNKPROJECT.SECURITYSETTINGS (SETTINGKEY, SETTINGVALUE, SETTINGTYPE, SETTINGDESC, UPDATEDBY, USEYN)
values ('SSL_CERT_EXPIRY', '2026-05-15', 'DATE', 'SSL 인증서 만료일', 'SYSTEM', 'Y');

COMMIT;


-- ADMIN 테이블에 로그인 실패 카운트 컬럼 추가
ALTER TABLE BNKPROJECT.ADMIN ADD (
      LOGINFAILCOUNT NUMBER DEFAULT 0,
      ACCOUNTLOCKED CHAR(1) DEFAULT 'N',
      LASTFAILEDLOGIN DATE
  );

COMMENT ON COLUMN BNKPROJECT.ADMIN.LOGINFAILCOUNT IS '로그인 실패 횟수';
  COMMENT ON COLUMN BNKPROJECT.ADMIN.ACCOUNTLOCKED IS '계정 잠금 여부 (Y/N)';
  COMMENT ON COLUMN BNKPROJECT.ADMIN.LASTFAILEDLOGIN IS '마지막 로그인 실패 시각';