-- 사이트 기본설정 테이블 생성
-- 작성자: 진원
-- 날짜: 2025-11-19
-- 내용: 푸터 정보 관리를 위한 사이트 설정 테이블

CREATE TABLE SITESETTINGS (
    SETTINGKEY VARCHAR2(50) PRIMARY KEY,
    SETTINGVALUE VARCHAR2(500) NOT NULL,
    SETTINGDESC VARCHAR2(200),
    UPDATEDDATE DATE DEFAULT SYSDATE,
    UPDATEDBY VARCHAR2(50)
);

-- 초기 데이터 삽입
INSERT INTO SITESETTINGS (SETTINGKEY, SETTINGVALUE, SETTINGDESC, UPDATEDBY)
VALUES ('CSPHONEDOMESTIC1', '1588-6200', '고객센터 전화번호1', 'SYSTEM');

INSERT INTO SITESETTINGS (SETTINGKEY, SETTINGVALUE, SETTINGDESC, UPDATEDBY)
VALUES ('CSPHONEDOMESTIC2', '1544-6200', '고객센터 전화번호2', 'SYSTEM');

INSERT INTO SITESETTINGS (SETTINGKEY, SETTINGVALUE, SETTINGDESC, UPDATEDBY)
VALUES ('CSPHONEOVERSEAS', '+82-2-1588-6200', '해외 전화번호', 'SYSTEM');

INSERT INTO SITESETTINGS (SETTINGKEY, SETTINGVALUE, SETTINGDESC, UPDATEDBY)
VALUES ('COPYRIGHTTEXT', 'COPYTRIGHT © 2014 BUSANBANK. ALL RIGHTS RESERVED.', '저작권 문구', 'SYSTEM');

INSERT INTO SITESETTINGS (SETTINGKEY, SETTINGVALUE, SETTINGDESC, UPDATEDBY)
VALUES ('APPNAME', 'Busanbank', '애플리케이션 이름', 'SYSTEM');

INSERT INTO SITESETTINGS (SETTINGKEY, SETTINGVALUE, SETTINGDESC, UPDATEDBY)
VALUES ('APPVERSION', '0.0.3-SNAPSHOT', '애플리케이션 버전', 'SYSTEM');

INSERT INTO SITESETTINGS (SETTINGKEY, SETTINGVALUE, SETTINGDESC, UPDATEDBY)
VALUES ('SITENAME', 'BNK 부산은행', '사이트명', 'SYSTEM');

INSERT INTO SITESETTINGS (SETTINGKEY, SETTINGVALUE, SETTINGDESC, UPDATEDBY)
VALUES ('COMPANYADDRESS', '부산광역시 중구 중앙대로 81', '회사 주소', 'SYSTEM');

INSERT INTO SITESETTINGS (SETTINGKEY, SETTINGVALUE, SETTINGDESC, UPDATEDBY)
VALUES ('COMPANYPHONE', '051-600-0400', '회사 대표 전화번호', 'SYSTEM');

COMMIT;
